### ISSUE TITLE
Loading native library in JNI

### ISSUE THREAD

**Issue by greco-salvatore** [devopvoid/webrtc-java#137]
**Describe the bug** && **To Reproduce**
Hi all, 
i'm testing the features of the library and i imported the library from maven in a Java 8 project. So far so good, but when im launching a simple main it returns this:

```
...
Hello world!
Exception in thread "main" java.lang.UnsatisfiedLinkError: dev.onvoid.webrtc.media.audio.AudioDeviceModule.initialize(Ldev/onvoid/webrtc/media/audio/AudioLayer;)V
	at dev.onvoid.webrtc.media.audio.AudioDeviceModule.initialize(Native Method)
	at dev.onvoid.webrtc.media.audio.AudioDeviceModule.<init>(AudioDeviceModule.java:40)
	at Main.initFactory(Main.java:44)
	at Main.main(Main.java:21)

Process finished with exit code 1
```

**Expected behavior**
the webrtc-java.dll contained in the maven library webrtc-java-0.8.0-windows-x86_64.jar is not found. For a workaround i extracted it manually in the root project an loaded it with `System.loadLibrary("webrtc-java");` (this is **OK**). It is an expected behavior?

btw i'm using IntellJ 2023.1, from the project structure/library i can specify the dll only like classpath and not like native library path...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 & IntellJ 2023.1
 - Version 0.8.0

**Additional context**

**Comment by greco-salvatore** [comment]
resolved
