### ISSUE TITLE
Maven install webrtc-java-jni fails

### ISSUE THREAD

**Issue by greco-salvatore** [devopvoid/webrtc-java#140]
**Describe the bug**
the maven install task fails during --WebRTC sync, causing --WebRTC generate and --WebRTC compile errors

**To Reproduce**
Simply launch maven install from scratch on webrtc-java-parent lifecycle

**Expected behavior**
Seems that a git fetch fails from origin, then other tasks cant complete

**Screenshots**
Logs:
```
"C:\Program Files\Java\jdk-18.0.1.1\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\Users\greco\git\webrtc-java -Djansi.passthrough=true "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\lib\idea_rt.jar=51276:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2023.1 install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] webrtc-java-parent                                                 [pom]
[INFO] webrtc-java-jni                                                    [pom]
[INFO] webrtc-java                                                        [jar]
[INFO] 
[INFO] ----------------< dev.onvoid.webrtc:webrtc-java-parent >----------------
[INFO] Building webrtc-java-parent 0.8.0                                  [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (base-compile) @ webrtc-java-parent ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ webrtc-java-parent ---
[INFO] Installing C:\Users\greco\git\webrtc-java\pom.xml to C:\Users\greco\.m2\repository\dev\onvoid\webrtc\webrtc-java-parent\0.8.0\webrtc-java-parent-0.8.0.pom
[INFO] 
[INFO] -----------------< dev.onvoid.webrtc:webrtc-java-jni >------------------
[INFO] Building webrtc-java-jni 0.8.0                                     [2/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- cmake-maven-plugin:3.22.1-b1:generate (cmake-generate) @ webrtc-java-jni ---
[INFO] Downloading binaries to C:\Users\greco\git\webrtc-java\webrtc-jni\target\dependency\cmake
[INFO] Configured Artifact: com.googlecode.cmake-maven-project:cmake-binaries:windows-x86_64:3.22.1-b1:jar
[INFO] cmake-binaries-3.22.1-b1-windows-x86_64.jar already unpacked.
[INFO] Executing C:\Users\greco\git\webrtc-java\webrtc-jni\target\dependency\cmake\bin\cmake.exe
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- WebRTC checkout path: C:/Users/greco/webrtc
-- WebRTC checkout branch: branch-heads/4844
-- WebRTC target CPU: x64
-- WebRTC build type: Release
-- WebRTC install path: C:/Users/greco/webrtc/build
-- WebRTC: fetch
Updating depot_tools...
Running: 'C:\Users\greco\AppData\Local\.vpython-root\store\python_venv-rru9ajq0d5gdrqhfnu07p9j6nk\contents\Scripts\python3.exe' 'C:\Users\greco\webrtc\depot_tools\gclient.py' root
Your current directory appears to already contain, or be part of, 
a checkout. "fetch" is used only to get new checkouts. Use 
"gclient sync" to update existing checkouts.

Fetch also does not yet deal with partial checkouts, so if fetch
failed, delete the checkout and start over (crbug.com/230691).
-- WebRTC: checkout "branch-heads/4844"
Updated 0 paths from the index
HEAD is now at 4d7f57adca [Merge M99] Check for valid transport before setting criteria.
-- WebRTC: sync
Updating depot_tools...
32>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "debe7d2d1982e540fbd6bd78604bf001753f9e74" "--no-tags"' in C:\Users\greco\webrtc\src\third_party\libFuzzer\src failed; will retry after a short nap...
32>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "debe7d2d1982e540fbd6bd78604bf001753f9e74" "--no-tags"' in C:\Users\greco\webrtc\src\third_party\libFuzzer\src failed; will retry after a short nap...
src/third_party/libFuzzer/src (ERROR)
----------------------------------------
[0:00:08] Started.
[0:00:08] Finished running: git rev-list -n 1 HEAD
[0:00:08] Finished running: git rev-parse --abbrev-ref=strict HEAD
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:10] fatal: expected 'acknowledgments'
[0:00:12] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:12] fatal: expected 'acknowledgments'
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin debe7d2d1982e540fbd6bd78604bf001753f9e74 --no-tags' returned non-zero exit status 128 in C:\Users\greco\webrtc\src\third_party\libFuzzer\src
-- WebRTC: generate
ERROR at //build/timestamp.gni:31:19: Script returned non-zero exit code.
build_timestamp = exec_script(compute_build_timestamp,
                  ^----------
Current dir: C:/Users/greco/webrtc/src/out/x64/
Command: C:/Users/greco/webrtc/depot_tools/bootstrap-2@3_11_6_chromium_30_bin/python3/bin/python3.exe C:/Users/greco/webrtc/src/build/compute_build_timestamp.py default
Returned 1.
See //build/config/win/BUILD.gn:12:1: whence it was imported.
import("//build/timestamp.gni")
^-----------------------------
See //build/config/BUILDCONFIG.gn:354:5: which caused the file to be included.
    "//build/config/win:default_crt",
    ^-------------------------------
C:\Users\greco\webrtc\src\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
C:\Users\greco\webrtc\src\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "C:\Users\greco\webrtc\src\build\compute_build_timestamp.py", line 126, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\greco\webrtc\src\build\compute_build_timestamp.py", line 112, in main
    last_commit_timestamp = int(open(lastchange_file).read())
                                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\greco\\webrtc\\src\\build\\util\\LASTCHANGE.committime'
Traceback (most recent call last):
  File "C:\Users\greco\webrtc\src\build\toolchain\win\setup_toolchain.py", line 314, in <module>
    main()
  File "C:\Users\greco\webrtc\src\build\toolchain\win\setup_toolchain.py", line 274, in main
    vc_lib_um_path = FindFileInEnvList(env, 'LIB', ';', 'user32.lib')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\greco\webrtc\src\build\toolchain\win\setup_toolchain.py", line 212, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: user32.lib is not found in LIB:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\lib\x86
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\lib\x86
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x86
Check if it is installed.
-- WebRTC: compile
ninja: Entering directory `out/x64'
ninja: error: loading 'build.ninja': Impossibile trovare il file specificato.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/greco/git/webrtc-java/webrtc-jni/target/windows-x86_64
[INFO] 
[INFO] --- cmake-maven-plugin:3.22.1-b1:compile (cmake-compile) @ webrtc-java-jni ---
[INFO] Downloading binaries to C:\Users\greco\git\webrtc-java\webrtc-jni\target\dependency\cmake
[INFO] Configured Artifact: com.googlecode.cmake-maven-project:cmake-binaries:windows-x86_64:3.22.1-b1:jar
[INFO] cmake-binaries-3.22.1-b1-windows-x86_64.jar already unpacked.
[INFO] Executing C:\Users\greco\git\webrtc-java\webrtc-jni\target\dependency\cmake\bin\cmake.exe
Versione di MSBuild L17.9.5+33de0b227 per .NET Framework

  jni-voithos.vcxproj -> C:\Users\greco\git\webrtc-java\webrtc-jni\target\windows-x86_64\dependencies\jni-voithos\Release\jni-voithos.lib
  pseudo.cxx
  webrtc.vcxproj -> C:\Users\greco\git\webrtc-java\webrtc-jni\target\windows-x86_64\dependencies\webrtc\Release\webrtc.lib
LINK : fatal error LNK1181: non � possibile aprire il file di input 'C:\Users\greco\webrtc\src\out\x64\obj\webrtc.lib' [C:\Users\greco\git\webrtc-java\webrtc-jni\target\windows-x86_64\webrtc-java.vcxproj]
[WARNING] Command: [C:\Users\greco\git\webrtc-java\webrtc-jni\target\dependency\cmake\bin\cmake.exe, --build, C:\Users\greco\git\webrtc-java\webrtc-jni\target\windows-x86_64, --target, install, --config, Release]
[WARNING] Directory: null
[WARNING] Environment: {USERDOMAIN_ROAMINGPROFILE=ZEPHYRUS-G15, NVM_SYMLINK=C:\Program Files\nodejs, PROCESSOR_LEVEL=25, SESSIONNAME=Console, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, GATEWAY_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\gateway.vmoptions, PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\PowerShell\Modules\, SystemDrive=C:, ACSvcPort=17532, RIDER_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\rider.vmoptions, USERNAME=greco, DEVECOSTUDIO_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\devecostudio.vmoptions, STUDIO_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\studio.vmoptions, ProgramFiles(x86)=C:\Program Files (x86), FPS_BROWSER_USER_PROFILE_STRING=Default, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, APPCODE_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\appcode.vmoptions, DriverData=C:\Windows\System32\Drivers\DriverData, OneDriveConsumer=C:\Users\greco\OneDrive, IntelliJ IDEA Community Edition=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\bin;, CLion=C:\Program Files\JetBrains\CLion 2023.1.1\bin;, DATASPELL_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\dataspell.vmoptions, ProgramData=C:\ProgramData, EFC_11744=1, ProgramW6432=C:\Program Files, HOMEPATH=\Users\greco, PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, windir=C:\Windows, =::=::\, PhpStorm=C:\Program Files\JetBrains\PhpStorm 2023.1\bin;, DATAGRIP_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\datagrip.vmoptions, LOCALAPPDATA=C:\Users\greco\AppData\Local, IntelliJ IDEA=C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\bin;, USERDOMAIN=ZEPHYRUS-G15, FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer, LOGONSERVER=\\ZEPHYRUS-G15, PYCHARM_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\pycharm.vmoptions, WEBSTORM_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\webstorm.vmoptions, JAVA_HOME=C:\Program Files\Java\jdk-18.0.1.1\bin\, CLION_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\clion.vmoptions, JETBRAINSCLIENT_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\jetbrainsclient.vmoptions, RlsSvcPort=22112, IDF_TOOLS_PATH=C:\Users\greco\.espressif, GOLAND_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\goland.vmoptions, OneDrive=C:\Users\greco\OneDrive, APPDATA=C:\Users\greco\AppData\Roaming, IDEA_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\idea.vmoptions, RUBYMINE_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\rubymine.vmoptions, JETBRAINS_CLIENT_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\jetbrains_client.vmoptions, M365_AES_AUDIO_KEY2=cf0cd30fa17639ab9a8fba388ad418c225e6926e4eec64abf86e6b1aabfa1ca9, VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\, CommonProgramFiles=C:\Program Files\Common Files, Path=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Users\greco\AppData\Local\Android\Sdk\platform-tools;C:\Users\greco\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\wamp64\bin\php\php8.0.26;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Users\greco\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Users\greco\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\greco\AppData\Local\Programs\Python\Python311\;C:\Users\greco\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\bin;;C:\Users\greco\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\JetBrains\PhpStorm 2023.1\bin;;C:\Users\greco\AppData\Roaming\Composer\vendor\bin;C:\Users\greco\.dotnet\tools;C:\Program Files\Microsoft Visual Studio\;C:\Users\greco\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin;C:\Users\greco\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\CLion 2023.1.1\bin;;C:\Program Files\JetBrains\IntelliJ IDEA 2023.1\bin;;C:\Program Files\Git\usr\bin;;C:\Program Files\Azure Data Studio\bin, OS=Windows_NT, COMPUTERNAME=ZEPHYRUS-G15, EnableLog=INFO, NVM_HOME=C:\Users\greco\AppData\Roaming\nvm, PROCESSOR_REVISION=4401, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\Windows\system32\cmd.exe, SystemRoot=C:\Windows, TEMP=C:\Users\greco\AppData\Local\Temp, WEBIDE_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\webide.vmoptions, HOMEDRIVE=C:, USERPROFILE=C:\Users\greco, TMP=C:\Users\greco\AppData\Local\Temp, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, NUMBER_OF_PROCESSORS=16, PHPSTORM_VM_OPTIONS=C:\Program Files\JetBrains\ja-netfilter-all\vmoptions\phpstorm.vmoptions, IDEA_INITIAL_DIRECTORY=C:\Users\greco\Desktop}
[WARNING] Exit code: 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for webrtc-java-parent 0.8.0:
[INFO] 
[INFO] webrtc-java-parent ................................. SUCCESS [  1.641 s]
[INFO] webrtc-java-jni .................................... FAILURE [ 37.291 s]
[INFO] webrtc-java ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.064 s
[INFO] Finished at: 2024-03-15T11:28:21+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.22.1-b1:compile (cmake-compile) on project webrtc-java-jni: Return code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :webrtc-java-jni

Process finished with exit code 1
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H1

**Additional context**
a normal git fetch complete correctly, then it's not a network issue

**Comment by singlerr** [comment]
Have you tried Visual Studio 2019? I had same issues with my Visual Studio 2022, but I solved the issue just removing Visual Studio 2022 and installing Visual Studio 2019

**Comment by SharankumarKsk** [comment]
Me too have the same issue using in IntelliJ IDEA. Did this resolved? @greco-salvatore  @singlerr

**Comment by SharankumarKsk** [comment]
@greco-salvatore My aim is to buid to 2 java application commnicating through WebRTC. Do we need to build webrtc-java-jni for that. Any help will be highy appreciable.

**Comment by singlerr** [comment]
@greco-salvatore you don't have to modify any codes. Just install Visual Studio Community 2019 and run build, then the buildscript will automatically detect msvc of Visual Studio 2019, resulting in no errors

**Comment by singlerr** [comment]
@SharankumarKsk sorry, my work with webrtc-java is currently private, but you can build webrtc with solution I've mentioned above

**Comment by SharankumarKsk** [comment]
Thank you @singlerr.

**Comment by greco-salvatore** [comment]
ok, just to be clear: the buildscript is looking for Visual Studio 2019 SDK instead of 2022 to build the webrtc-jni project, as a part of the webrtc java project that can be managed via a generic java IDE. I will try it. I suppose the git fetch errors are ignored then. Thank you
