### ISSUE TITLE
When webrtc-java join a new room created by appr.tc, a critical error occurred: Duplicated register request

### ISSUE THREAD

**Issue by HenryZhouHB** [devopvoid/webrtc-java#16]
When webrtc-java join a new room created by appr.tc, a critical error occurred: Duplicated register request. The log is as follow:
2021-04-14 14:00:22.350 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: WebSocket connection opened
2021-04-14 14:00:22.351 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Registering WebSocket
2021-04-14 14:00:22.355 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"cmd":"register","roomid":"fvfvfv","clientid":"36340910"}
2021-04-14 14:00:23.772 [INFO     ] dev.onvoid.webrtc.demo.net.PeerConnectionClient: Track "audioTrack" set enabled to "true"
2021-04-14 14:00:23.837 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"answer","sdp":"v=0\r\no=- 1419087351138574516 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS stream\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Y+ZR\r\na=ice-pwd:ny8tG9jKc1Er/mIoeptaa2qR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 18:4E:28:35:EE:4F:1E:FB:8C:56:62:6F:90:BC:13:13:7A:78:2D:C7:08:D2:B4:6C:CB:33:EC:9B:F0:28:E5:04\r\na=setup:active\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:stream 14127308-1c0e-4e54-8df6-abdb4430ef9e\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:2400173004 cname:k+1CE4ox9CvNMoY9\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 122 125 121 124\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Y+ZR\r\na=ice-pwd:ny8tG9jKc1Er/mIoeptaa2qR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 18:4E:28:35:EE:4F:1E:FB:8C:56:62:6F:90:BC:13:13:7A:78:2D:C7:08:D2:B4:6C:CB:33:EC:9B:F0:28:E5:04\r\na=setup:active\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:stream ac44247e-1d92-4d37-81a3-bbf39473c34d\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 AV1X/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=127\r\na=rtpmap:125 red/90000\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=125\r\na=rtpmap:124 ulpfec/90000\r\na=ssrc-group:FID 2760260105 4227803340\r\na=ssrc:2760260105 cname:k+1CE4ox9CvNMoY9\r\na=ssrc:4227803340 cname:k+1CE4ox9CvNMoY9\r\n"}
2021-04-14 14:00:23.843 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:730747204 1 udp 2122260223 169.254.59.114 57780 typ host generation 0 ufrag Y+ZR network-id 1"}
2021-04-14 14:00:23.846 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: WSS->C: {"msg":"","error":"Duplicated register request"}
2021-04-14 14:00:23.846 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:3420997037 1 udp 2122194687 192.168.31.136 57781 typ host generation 0 ufrag Y+ZR network-id 2"}
2021-04-14 14:00:23.849 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Duplicated register request
2021-04-14 14:00:23.850 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:2999745851 1 udp 2122129151 192.168.56.1 57782 typ host generation 0 ufrag Y+ZR network-id 3"}
2021-04-14 14:00:23.854 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:124090942 1 udp 1685987071 172.17.0.1 59110 typ srflx raddr 192.168.31.136 rport 57781 generation 0 ufrag Y+ZR network-id 2"}
2021-04-14 14:00:23.854 [INFO     ] dev.onvoid.webrtc.demo.net.PeerConnectionClient: Track "videoTrack" set enabled to "true"
2021-04-14 14:00:23.855 [INFO     ] dev.onvoid.webrtc.demo.net.PeerConnectionClient: Add 12 remote candidates
2021-04-14 14:00:23.857 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Send message failed
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendClose(TransportImpl.java:271)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendClose0(WebSocketImpl.java:337)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendCloseSilently(WebSocketImpl.java:652)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.lambda$processClose$0(WebSocketImpl.java:541)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processClose(WebSocketImpl.java:536)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:451)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.trySetState(WebSocketImpl.java:837)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.signalClose(WebSocketImpl.java:763)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onClose(WebSocketImpl.java:814)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.endFrame(MessageDecoder.java:257)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:475)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:665)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:762)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:844)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:968)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:923)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:923)

2021-04-14 14:00:23.895 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:2032080525 1 udp 41819903 172.17.0.2 60831 typ relay raddr 172.17.0.1 rport 59110 generation 0 ufrag Y+ZR network-id 2"}
2021-04-14 14:00:23.895 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Send message failed
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendWebSocketMessage(AppRTCWebSocketClient.java:351)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendIceCandidate(AppRTCWebSocketClient.java:456)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.send(AppRTCWebSocketClient.java:216)
	at dev.onvoid.webrtc.demo.net.PeerConnectionClient.onIceCandidate(PeerConnectionClient.java:197)

2021-04-14 14:00:23.943 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:1695395252 1 tcp 1518280447 169.254.59.114 60194 typ host tcptype passive generation 0 ufrag Y+ZR network-id 1"}
2021-04-14 14:00:23.943 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Send message failed
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendWebSocketMessage(AppRTCWebSocketClient.java:351)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendIceCandidate(AppRTCWebSocketClient.java:456)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.send(AppRTCWebSocketClient.java:216)
	at dev.onvoid.webrtc.demo.net.PeerConnectionClient.onIceCandidate(PeerConnectionClient.java:197)

2021-04-14 14:00:23.946 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:2238429533 1 tcp 1518214911 192.168.31.136 60197 typ host tcptype passive generation 0 ufrag Y+ZR network-id 2"}
2021-04-14 14:00:23.947 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Send message failed
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendWebSocketMessage(AppRTCWebSocketClient.java:351)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendIceCandidate(AppRTCWebSocketClient.java:456)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.send(AppRTCWebSocketClient.java:216)
	at dev.onvoid.webrtc.demo.net.PeerConnectionClient.onIceCandidate(PeerConnectionClient.java:197)

2021-04-14 14:00:23.949 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: C->WSS: {"type":"candidate","label":0,"id":"0","candidate":"candidate:4233069003 1 tcp 1518149375 192.168.56.1 60200 typ host tcptype passive generation 0 ufrag Y+ZR network-id 3"}
2021-04-14 14:00:23.949 [CRITICAL ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Send message failed
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendWebSocketMessage(AppRTCWebSocketClient.java:351)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.sendIceCandidate(AppRTCWebSocketClient.java:456)
	at dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient.send(AppRTCWebSocketClient.java:216)
	at dev.onvoid.webrtc.demo.net.PeerConnectionClient.onIceCandidate(PeerConnectionClient.java:197)

2021-04-14 14:04:12.480 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Leaving room
2021-04-14 14:04:12.480 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Disconnecting WebSocket
2021-04-14 14:04:12.480 [INFO     ] dev.onvoid.webrtc.demo.apprtc.AppRTCWebSocketClient: Disconnecting WebSocket done

**Comment by devopvoid** [comment]
I won't fix the AppRTC code. It's just for demo purposes.
