### ISSUE TITLE
Latest native libraries are not available on Maven Central

### ISSUE THREAD

**Issue by fioan89** [devopvoid/webrtc-java#70]
There is an issue when loading the native library on Windows. I throws:
`
Exception in thread "main" java.lang.NoSuchMethodError: <init>
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at dev.onvoid.webrtc.internal.NativeLoader.loadLibrary(NativeLoader.java:71)
	at dev.onvoid.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:42)`

In build.gradle.kts I declared the following:

```
implementation("dev.onvoid.webrtc:webrtc-java:0.6.0")
implementation("dev.onvoid.webrtc:webrtc-java-windows-x86_64:0.1.0")```

0.1.0 is the only JNI dependency published on MVN Central. In the end I've downloaded webrtc-jar and libwebrtc and did my own build. Still, it would have been nice to have the latest native libraries uploaded on the maven repo. 

Thank you for your understanding .

**Comment by fioan89** [comment]
The problem does not reproduce if I downgrade `webrtc-java` to `0.30` .

**Comment by thelsing** [comment]
See #23
